### PR TITLE
change the copyright year from 2015 to 2016.

### PR DESCRIPTION
**Pull request by vpuff**

### CODE REVIEW

**Comment by ronkorving** [comment]
You need to rebuild before changes take effect. cc @baptistebrunet @everydayfoxlife

**Comment by everydayfoxlife** [comment]
If it's just the html file being updated then no need to rebuild (since assets aren't affected).

**Comment by vpuff** [comment]
@ronkorving I'm not familiar with the process. What I need to do to get this modification on prod?

**Comment by ronkorving** [comment]
@vpuff as @everydayfoxlife pointed out, I was wrong and there is no problem.

**Comment by vpuff** [comment]
Sweet. So what should be done now?

On Fri, Jan 29, 2016 at 12:38 PM, Ron Korving <notifications@github.com>
wrote:

> @vpuff <https://github.com/vpuff> as @everydayfoxlife
> <https://github.com/everydayfoxlife> pointed out, I was wrong and there
> is no problem.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Wizcorp/wizcorpsite/pull/39#issuecomment-176555272>.
>



-- 
<http://www.wizcorp.jp/> Vincent Pieffet
Project Manager | Wizcorp Inc. <http://www.wizcorp.jp/>
------------------------------
TECH . GAMING . OPEN-SOURCE WIZARDS
+ 81 (0)3-4550-1448|Website <http://www.wizcorp.jp/>|Twitter
<https://twitter.com/Wizcorp>|Facebook <http://www.facebook.com/Wizcorp>|
LinkedIn <http://www.linkedin.com/company/wizcorp>

**Pull request merged**
